<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Role extends \Entities\Role implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getRolId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["rolId"];
        }
        $this->__load();
        return parent::getRolId();
    }

    public function setRolAjouterDisque($rolAjouterDisque)
    {
        $this->__load();
        return parent::setRolAjouterDisque($rolAjouterDisque);
    }

    public function getRolAjouterDisque()
    {
        $this->__load();
        return parent::getRolAjouterDisque();
    }

    public function setRolModifierDisque($rolModifierDisque)
    {
        $this->__load();
        return parent::setRolModifierDisque($rolModifierDisque);
    }

    public function getRolModifierDisque()
    {
        $this->__load();
        return parent::getRolModifierDisque();
    }

    public function setRolSupprimerDisque($rolSupprimerDisque)
    {
        $this->__load();
        return parent::setRolSupprimerDisque($rolSupprimerDisque);
    }

    public function getRolSupprimerDisque()
    {
        $this->__load();
        return parent::getRolSupprimerDisque();
    }

    public function setRolLireFiche($rolLireFiche)
    {
        $this->__load();
        return parent::setRolLireFiche($rolLireFiche);
    }

    public function getRolLireFiche()
    {
        $this->__load();
        return parent::getRolLireFiche();
    }

    public function setRolRechercher($rolRechercher)
    {
        $this->__load();
        return parent::setRolRechercher($rolRechercher);
    }

    public function getRolRechercher()
    {
        $this->__load();
        return parent::getRolRechercher();
    }

    public function setRolImporter($rolImporter)
    {
        $this->__load();
        return parent::setRolImporter($rolImporter);
    }

    public function getRolImporter()
    {
        $this->__load();
        return parent::getRolImporter();
    }

    public function setRolAjouterPret($rolAjouterPret)
    {
        $this->__load();
        return parent::setRolAjouterPret($rolAjouterPret);
    }

    public function getRolAjouterPret()
    {
        $this->__load();
        return parent::getRolAjouterPret();
    }

    public function setRolModifierPret($rolModifierPret)
    {
        $this->__load();
        return parent::setRolModifierPret($rolModifierPret);
    }

    public function getRolModifierPret()
    {
        $this->__load();
        return parent::getRolModifierPret();
    }

    public function setRolSupprimerPret($rolSupprimerPret)
    {
        $this->__load();
        return parent::setRolSupprimerPret($rolSupprimerPret);
    }

    public function getRolSupprimerPret()
    {
        $this->__load();
        return parent::getRolSupprimerPret();
    }

    public function setRolLirePret($rolLirePret)
    {
        $this->__load();
        return parent::setRolLirePret($rolLirePret);
    }

    public function getRolLirePret()
    {
        $this->__load();
        return parent::getRolLirePret();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'rolId', 'rolAjouterDisque', 'rolModifierDisque', 'rolSupprimerDisque', 'rolLireFiche', 'rolRechercher', 'rolImporter', 'rolAjouterPret', 'rolModifierPret', 'rolSupprimerPret', 'rolLirePret');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}