<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Categorie extends \Entities\Categorie implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getCatId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["catId"];
        }
        $this->__load();
        return parent::getCatId();
    }

    public function setCatLibelle($catLibelle)
    {
        $this->__load();
        return parent::setCatLibelle($catLibelle);
    }

    public function getCatLibelle()
    {
        $this->__load();
        return parent::getCatLibelle();
    }

    public function setRad(\Entities\Radio $rad = NULL)
    {
        $this->__load();
        return parent::setRad($rad);
    }

    public function getRad()
    {
        $this->__load();
        return parent::getRad();
    }

    public function setRol(\Entities\Role $rol = NULL)
    {
        $this->__load();
        return parent::setRol($rol);
    }

    public function getRol()
    {
        $this->__load();
        return parent::getRol();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'catId', 'catLibelle', 'rad', 'rol');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}